
###
GET /api/v1/security/csrf-token
Host: localhost:9000
Accept: text/plain



### Identity Requests



###
POST /api/v1/identities/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json

{
    "authority": "ADMIN",
    "username": "burgasvv",
    "password": "burgasvv",
    "email": "burgasvv@gmail.com",
    "isActive": true
}

###
POST /api/v1/identities/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: bff8fb3d-12ac-4ec2-af45-2d8ba2e718a1

{
    "authority": "USER",
    "username": "zagor",
    "password": "zagor",
    "email": "zagor@gmail.com",
    "isActive": true
}

###
POST /api/v1/identities/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: cbc4404b-5143-42c4-b6db-2155a495a63f

{
    "authority": "USER",
    "username": "danakt",
    "password": "danakt",
    "email": "danakt@gmail.com",
    "isActive": true
}

###
GET /api/v1/identities
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET /api/v1/identities/by-id?identityId=5d755809-d1df-4506-887c-90bb0425b612
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
PUT /api/v1/identities/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Authorization: Basic burgasvv@gmail.com burgasvv
Origin: http://localhost:9000
X-Csrf-Token: 0301feb0-df34-42ec-a5b4-d66e1cc00185

{
    "id": "5d755809-d1df-4506-887c-90bb0425b612",
    "username": "burgasvv"
}

###
PUT /api/v1/identities/change-password?identityId=5d755809-d1df-4506-887c-90bb0425b612&newPassword=burgasvv
Host: localhost:9000
Accept: application/json

###
DELETE /api/v1/identities/delete?identityId=ffac79b7-28e4-42ad-bb5b-e11e0d978acf
Host: localhost:9000
Accept: application/json

###
PUT /api/v1/identities/deactivate?identityId=5d755809-d1df-4506-887c-90bb0425b612
Host: localhost:9000
Accept: application/json

###
PUT /api/v1/identities/activate?identityId=5d755809-d1df-4506-887c-90bb0425b612
Host: localhost:9000
Accept: application/json

###
DELETE /api/v1/identities/remove-files?identityId=033c7dcf-b8a2-498f-8a6b-eafde06ba57d&
    fileId=1c6582e3-23e0-4f7a-8024-4e2d732ce51c&fileId=ced29ce7-3b86-4d9c-8e65-416bd82d6ead
Host: localhost:9000
Accept: application/json



### Restaurant Requests



###
POST /api/v1/restaurants/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 044f1ec9-3d34-4952-be3b-63eabe80e9af

{
    "name": "ShashlickON",
    "description": "Description of restaurant ShashlickON"
}

###
GET /api/v1/restaurants/by-id?restaurantId=da31afc2-3d1e-418f-b64f-d4f0a85b0f16
Host: localhost:9000
Accept: application/json

###
GET /api/v1/restaurants
Host: localhost:9000
Accept: application/json

###
PUT /api/v1/restaurant/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 38dd6a47-895e-43fc-af15-4ada46b853ca

{
    "id": "67473842-72dd-450c-81d1-98fa9de9f0d6",
    "description": "Description of restaurant ShashlickON. 2024 year"
}

###
DELETE /api/v1/restaurants/delete?restaurantId=24c6fc2b-9fde-4c85-9eb1-641e875157b7
Host: localhost:9000
Accept: application/json
Origin: http://localhost:9000
X-Csrf-Token: 55a044e9-7578-4559-bfb3-43096fabfcfa



### Location Requests



###
POST /api/v1/locations/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: b1dc2964-6cd5-46e1-8a7a-bec79e1e7f3f

{
    "restaurantId": "8d0a5e94-03d1-4dd3-b0c1-979099d0f80f",
    "address": {
        "city": "Moscow",
        "street": "Sverdlova",
        "house": "43b",
        "apartment": "34"
    },
    "open": "08:00",
    "close": "21:00"
}

###
GET /api/v1/locations
Host: localhost:9000
Accept: application/json

###
GET /api/v1/locations/by-id?restaurantId=da31afc2-3d1e-418f-b64f-d4f0a85b0f16&addressId=a1590462-5dc1-4b47-a525-012346966a18
Host: localhost:9000
Accept: application/json

###
PUT /api/v1/locations/update?restaurantId=67473842-72dd-450c-81d1-98fa9de9f0d6&addressId=b8426fe2-cee6-4b36-8f10-5e58d73d121c
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 51e43e2f-3765-4e7a-b0f4-63024afe2945

{
    "address": {
        "city": "Saint-Petersburg",
        "street": "Morskaya",
        "house": "78/4",
        "apartment": "12"
    }
}

###
DELETE /api/v1/locations/delete?restaurantId=67473842-72dd-450c-81d1-98fa9de9f0d6&addressId=1a67168f-ba15-435e-a202-207ec71fe65c
Host: localhost:9000
Accept: application/json
Origin: http://localhost:9000
X-Csrf-Token: eaec7467-8d2b-41bc-ad1e-c3c2633f3362



### Employee Requests



###
POST /api/v1/employees/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 379dab07-469e-432f-a73e-4e5b0a54189e
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "identityId": "5d755809-d1df-4506-887c-90bb0425b612",
    "position": "DIRECTOR",
    "firstname": "Burgas",
    "lastname": "Vyacheslav",
    "patronymic": "Vasil'evich",
    "age": 32,
    "birthday": "1993-01-10",
    "employeeAddress": {
        "city": "Novosibirsk",
        "street": "Ivanova",
        "house": "28",
        "apartment": "48"
    }
}

###
POST /api/v1/employees/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: a5239796-99d1-4626-b492-9d0ea4397987
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "identityId": "010b14de-23b4-423d-9191-ba9e488bffe7",
    "position": "MANAGER",
    "locationRestaurantId": "8d0a5e94-03d1-4dd3-b0c1-979099d0f80f",
    "locationAddressId": "5950e235-4690-4702-87da-6e4878c1ae43",
    "firstname": "Zagorul'ko",
    "lastname": "Boris",
    "patronymic": "Jur'evich",
    "age": 32,
    "birthday": "1993-10-30",
    "employeeAddress": {
        "city": "Moscow",
        "street": "Chekaeva",
        "house": "52",
        "apartment": "139"
    }
}

###
POST /api/v1/employees/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: a5239796-99d1-4626-b492-9d0ea4397987
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "identityId": "cf919d59-1342-4ede-a75a-ffe80ef1f9b8",
    "position": "SERVANT",
    "locationRestaurantId": "8d0a5e94-03d1-4dd3-b0c1-979099d0f80f",
    "locationAddressId": "5950e235-4690-4702-87da-6e4878c1ae43",
    "firstname": "Molchanov",
    "lastname": "Zair",
    "patronymic": "Viktorovich",
    "age": 31,
    "birthday": "1994-12-12",
    "employeeAddress": {
        "city": "Saint-Petersburg",
        "street": "Martova",
        "house": "23/1",
        "apartment": "12"
    }
}

###
GET /api/v1/employees
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET /api/v1/employees/by-restaurant?restaurantId=8d0a5e94-03d1-4dd3-b0c1-979099d0f80f
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET /api/v1/employees/by-id?employeeId=2d5770c1-8a8a-463e-84b5-faaf59512755
Host: localhost:9000
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET /api/v1/employees/by-id?employeeId=9bb9169a-f327-4bad-a1cb-e18125d9168c
Host: localhost:9000
Accept: application/json
Authorization: Basic zagor@gmail.com zagor

###
PUT /api/v1/employees/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: e78d2b33-6580-4995-b87f-34d5c00262a6
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "id": "2d5770c1-8a8a-463e-84b5-faaf59512755",
    "identityId": "5d755809-d1df-4506-887c-90bb0425b612",
    "locationRestaurantId": "8d0a5e94-03d1-4dd3-b0c1-979099d0f80f",
    "locationAddressId": "5950e235-4690-4702-87da-6e4878c1ae43"
}

###
PUT /api/v1/employees/add-servant?directorId=2d5770c1-8a8a-463e-84b5-faaf59512755&servantId=d29dab8c-a6c0-4c4c-b793-a093a8fe4713
Host: localhost:9000
Accept: application/json
Origin: http://localhost:9000
X-Csrf-Token: 0f3cb94d-5ea9-4437-9a6e-4a95eedc1995
Authorization: Basic burgasvv@gmail.com burgasvv

###
DELETE /api/v1/employees/remove-servant?directorId=4f9da711-b3ae-4079-a7fe-4861317f27c0&servantId=9ab19edd-d37a-48da-8e1a-1f84f44033ec
Host: localhost:9000
Accept: application/json
Origin: http://localhost:9000
X-Csrf-Token: a6857592-af17-48cd-aece-fd1c43ea9bb3
Authorization: Basic burgasvv@gmail.com burgasvv



### Reservation Requests



###
POST /api/v1/reservations/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 5b080341-0383-4d3f-9297-c0639bca8a2a

{
    "locationRestaurantId": "8d0a5e94-03d1-4dd3-b0c1-979099d0f80f",
    "locationAddressId": "5950e235-4690-4702-87da-6e4878c1ae43",
    "name": "Rogov Aleksei Pavlovich",
    "phone": "+79139056754",
    "places": 10,
    "startTime": "2025-11-28T18:30"
}

###
POST /api/v1/reservations/create
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: a64f1c81-dfc5-4e0d-8b0e-9ca72fe0d2a8

{
    "locationRestaurantId": "8d0a5e94-03d1-4dd3-b0c1-979099d0f80f",
    "locationAddressId": "5950e235-4690-4702-87da-6e4878c1ae43",
    "name": "Treev Alexander Dmitrievich",
    "phone": "+79324568943",
    "places": 25,
    "startTime": "2025-11-28T15:30"
}

###
GET /api/v1/reservations/by-client
Host: localhost:9000
Accept: application/json
Content-Type: application/json

{
    "name": "Rogov Aleksei Pavlovich",
    "phone": "+79139056754"
}

###
PUT /api/v1/reservations/update
Host: localhost:9000
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9000
X-Csrf-Token: 0b7f8cd6-80cd-4ac2-9fb3-90fa5a4add29

{
    "id": "57f05588-a845-4e46-bdca-7891abfeb9a6",
    "places": 25
}